### ISSUE TITLE
Hep with set up

### ISSUE THREAD

**Issue by cronos45** [nickzman/rainingcubes#1]
Download binary, and run in Xcode but nothing happens. Can you please tell me what to do

**Comment by nickzman** [comment]
What are you trying? The binary isn't run in Xcode.

**Comment by cronos45** [comment]
My mistake, I thought it was. When you say binary I am unsure which file. I thought this was a metal app to test with OS X

**Comment by nickzman** [comment]
This is a screen saver, not an app. You download the DMG binary, double-click on it to mount it (if your browser doesn't already do that step for you), and then right-click on the screen saver and choose "open" to have System Preferences install it. After that, you can select it and change its preferences in System Preferences -> Desktop & Screen Saver -> Screen Saver -> RainingCubes.

**Comment by cronos45** [comment]
When downloaded It is automatically unzipped and i can not see a DMG anywhere, I know the hub is not for support, So I truly appreciate you taking some time to help.

**Comment by nickzman** [comment]
The binary posted under "releases" is a DMG. If you downloaded a ZIP, then you downloaded the source code instead of the binary. If you don't want to build your own binary, then download the DMG instead.

**Comment by cronos45** [comment]
Thank you, I can't wait to try it out once I get home

**Comment by cronos45** [comment]
Its alive, I thank you again and I do indeed love the raining cubes screen saver. Thank you!
