### ISSUE TITLE
Your Os does not support metal.

### ISSUE THREAD

**Issue by SnippyValson** [nickzman/rainingcubes#3]
I downloaded the project and build it. When I tried to start the screensaver after installing it from the debug folder I'm getting an error saying "Your version of the os does not support metal." I'm running MacOs Catalina on Macbook Pro 13, 2019.

![Screenshot 2020-08-31 at 1 04 27 AM](https://user-images.githubusercontent.com/6286103/91667936-ecf4b980-eb25-11ea-9210-490ac34bf302.png)

**Comment by nickzman** [comment]
Oops. Thanks for telling me.
